from codeable_models import CClass, CBundle, add_links, CStereotype, CMetaclass, CEnum, CAttribute 
from metamodels.microservice_dfds_metamodel import * 
from plant_uml_renderer import PlantUMLGenerator 
plantuml_path = "../../plantuml.jar" 
output_directory = "." 
model_name = "train-ticket-0.0.1_a0209ef"
ts_contacts_service = CClass(service, "ts-contacts-service", stereotype_instances = [internal], tagged_values = {'Endpoints': "['/contacts/findAll', '/contacts/modifyContacts', '/contacts/update', '/welcome', '/contacts/create', '/contacts/delete', '/contacts/getContactsById', '/contacts/admincreate', '/contacts/deleteContacts', '/contacts/findContacts']", 'Port': 12347})
ts_admin_user_service = CClass(service, "ts-admin-user-service", stereotype_instances = [internal], tagged_values = {'Endpoints': "['/adminuser/deleteUser', '/welcome', '/adminuser/findAll/{id}', '/adminuser/updateUser', '/adminuser/addUser']", 'Port': 16115})
ts_food_map_service = CClass(service, "ts-food-map-service", stereotype_instances = [internal], tagged_values = {'Endpoints': "['/welcome', '/foodmap/getTrainFoodOfTrip', '/foodmap/getAllTrainFood', '/foodmap/getAllFoodStores', '/foodmap/getFoodStoresOfStation']", 'Port': 18855})
ts_notification_service = CClass(service, "ts-notification-service", stereotype_instances = [internal], tagged_values = {'Port': 17853, 'Endpoints': "['/welcome', '/notification/order_cancel_success', '/notification/preserve_success', '/notification/order_changed_success', '/notification/order_create_success']"})
ts_login_service = CClass(service, "ts-login-service", stereotype_instances = [internal], tagged_values = {'Port': 12342, 'Endpoints': "['/logout', '/login', '/welcome']"})
ts_cancel_service = CClass(service, "ts-cancel-service", stereotype_instances = [internal], tagged_values = {'Endpoints': "['/cancelOrder', '/cancelCalculateRefund', '/welcome']", 'Port': 18885})
ts_config_service = CClass(service, "ts-config-service", stereotype_instances = [internal], tagged_values = {'Port': 15679, 'Endpoints': "['/config/retrieve', '/welcome', '/config/update', '/config/query', '/config/delete', '/config/queryAll', '/config/create']"})
ts_assurance_service = CClass(service, "ts-assurance-service", stereotype_instances = [internal], tagged_values = {'Endpoints': "['/assurance/modifyAssurance', '/welcome', '/assurance/deleteAssuranceByOrderId', '/assurance/findAssuranceByOrderId', '/assurance/create', '/assurance/deleteAssurance', '/assurance/getAssuranceById', '/assurance/findAll', '/assurance/getAllAssuranceType']", 'Port': 18888})
ts_order_other_service = CClass(service, "ts-order-other-service", stereotype_instances = [internal], tagged_values = {'Endpoints': "['/orderOther/modifyOrderStatus', '/orderOther/delete', '/welcome', '/orderOther/findAll', '/orderOther/calculate', '/orderOther/payOrder', '/orderOther/create', '/orderOther/getById', '/orderOther/getTicketListByDateAndTripId', '/orderOther/queryForRefresh', '/orderOther/query', '/orderOther/update', '/orderOther/adminUpdate', '/orderOther/adminAddOrder', '/getOrderOtherInfoForSecurity', '/orderOther/price']", 'Port': 12032})
ts_route_service = CClass(service, "ts-route-service", stereotype_instances = [internal], tagged_values = {'Port': 11178, 'Endpoints': "['/route/delete', '/welcome', '/route/createAndModify', '/route/queryAll', '/route/queryByStartAndTerminal', '/route/queryById/{routeId}']"})
ts_price_service = CClass(service, "ts-price-service", stereotype_instances = [internal], tagged_values = {'Port': 16579, 'Endpoints': "['/price/query', '/welcome', '/price/queryAll', '/price/delete', '/price/create', '/price/update']"})
ts_preserve_service = CClass(service, "ts-preserve-service", stereotype_instances = [internal], tagged_values = {'Port': 14568, 'Endpoints': "['/preserve', '/welcome']"})
micro_service_monitoring_core = CClass(service, "micro-service-monitoring-core", stereotype_instances = [internal, local_logging])
ts_security_service = CClass(service, "ts-security-service", stereotype_instances = [internal], tagged_values = {'Endpoints': "['/welcome', '/securityConfig/findAll', '/security/check', '/securityConfig/delete', '/securityConfig/update', '/securityConfig/create']", 'Port': 11188})
ts_consign_service = CClass(service, "ts-consign-service", stereotype_instances = [internal], tagged_values = {'Port': 16111, 'Endpoints': "['/consign/findByAccountId/{id}', '/welcome', '/consign/findByConsignee', '/consign/updateConsign', '/consign/insertConsign']"})
ts_train_service = CClass(service, "ts-train-service", stereotype_instances = [internal, local_logging], tagged_values = {'Port': 14567, 'Endpoints': "['/train/query', '/train/update', '/train/create', '/welcome', '/train/delete', '/train/retrieve']"})
ts_order_service = CClass(service, "ts-order-service", stereotype_instances = [internal], tagged_values = {'Endpoints': "['/getOrderInfoForSecurity', '/order/calculate', '/order/delete', '/welcome', '/order/modifyOrderStatus', '/order/query', '/order/update', '/order/getById', '/order/adminUpdate', '/order/payOrder', '/order/price', '/order/adminAddOrder', '/order/findAll', '/order/getTicketListByDateAndTripId', '/order/queryForRefresh', '/order/create']", 'Port': 12031})
ts_verification_code_service = CClass(service, "ts-verification-code-service", stereotype_instances = [internal], tagged_values = {'Port': 15678, 'Endpoints': "['/error', '/verification/generate', '/verification/verify']"})
ts_food_service = CClass(service, "ts-food-service", stereotype_instances = [internal], tagged_values = {'Port': 18856, 'Endpoints': "['/welcome', '/food/createFoodOrder', '/food/cancelFoodOrder', '/food/findFoodOrderByOrderId', '/food/updateFoodOrder', '/food/findAllFoodOrder', '/food/getFood']"})
ts_rebook_service = CClass(service, "ts-rebook-service", stereotype_instances = [internal], tagged_values = {'Endpoints': "['/rebook/rebook', '/rebook/payDifference', '/welcome']", 'Port': 18886})
rest_service_5 = CClass(service, "rest-service-5", stereotype_instances = [internal, local_logging], tagged_values = {'Port': 16005, 'Endpoints': "['/monitor', '/hello5']"})
rest_service_2 = CClass(service, "rest-service-2", stereotype_instances = [internal, local_logging], tagged_values = {'Endpoints': "['/hello', '/hello2']", 'Port': 16002})
rest_service_collector = CClass(service, "rest-service-collector", stereotype_instances = [internal, local_logging], tagged_values = {'Port': 16001, 'Endpoints': "['/api/v1/spans', '/api/**', '/**']"})
rest_service_3 = CClass(service, "rest-service-3", stereotype_instances = [internal, local_logging], tagged_values = {'Endpoints': "['/hello3', '/hello']", 'Port': 16003})
rest_service_4 = CClass(service, "rest-service-4", stereotype_instances = [internal, local_logging], tagged_values = {'Port': 16004, 'Endpoints': "['/hello4', '/getdata', '/getdata1']"})
rest_service_1 = CClass(service, "rest-service-1", stereotype_instances = [internal, local_logging], tagged_values = {'Endpoints': "['/hello', '/hello1']", 'Port': 16001})
rest_service_6 = CClass(service, "rest-service-6", stereotype_instances = [internal, local_logging], tagged_values = {'Endpoints': "['/hello6_1', '/hello6']", 'Port': 16006})
rest_service_end = CClass(service, "rest-service-end", stereotype_instances = [internal, local_logging], tagged_values = {'Port': 16000, 'Endpoints': "['/greeting', '/test']"})
ts_ui_test = CClass(service, "ts-ui-test", stereotype_instances = [internal])
ts_register_service = CClass(service, "ts-register-service", stereotype_instances = [internal], tagged_values = {'Port': 12344, 'Endpoints': "['/register', '/welcome']"})
spring_transaction_consumer = CClass(service, "spring-transaction-consumer", stereotype_instances = [internal])
ts_admin_basic_info_service = CClass(service, "ts-admin-basic-info-service", stereotype_instances = [internal], tagged_values = {'Port': 18767, 'Endpoints': "['/adminbasic/deleteStation', '/adminbasic/modifyContacts', '/adminbasic/getAllConfigs/{id}', '/adminbasic/deletePrice', '/adminbasic/getAllPrices/{id}', '/adminbasic/deleteTrain', '/adminbasic/getAllStations/{id}', '/adminbasic/getAllTrains/{id}', '/adminbasic/modifyTrain', '/adminbasic/modifyConfig', '/adminbasic/addPrice', '/adminbasic/addStation', '/adminbasic/deleteConfig', '/adminbasic/addTrain', '/adminbasic/modifyStation', '/welcome', '/adminbasic/addContacts', '/adminbasic/modifyPrice', '/adminbasic/deleteContacts', '/adminbasic/getAllContacts/{id}', '/adminbasic/addConfig']"})
ts_consign_price_service = CClass(service, "ts-consign-price-service", stereotype_instances = [internal], tagged_values = {'Endpoints': "['/consignPrice/getPrice', '/welcome', '/consignPrice/getPriceInfo', '/consignPrice/modifyPriceConfig', '/consignPrice/getPriceConfig']", 'Port': 16110})
ts_basic_service = CClass(service, "ts-basic-service", stereotype_instances = [internal], tagged_values = {'Endpoints': "['/basic/queryForTravel', '/welcome', '/basic/queryForStationId']", 'Port': 15680})
ts_preserve_other_service = CClass(service, "ts-preserve-other-service", stereotype_instances = [internal], tagged_values = {'Endpoints': "['/preserveOther', '/welcome']", 'Port': 14569})
ts_station_service = CClass(service, "ts-station-service", stereotype_instances = [internal], tagged_values = {'Port': 12345, 'Endpoints': "['/welcome', '/station/queryForIdBatch', '/station/create', '/station/exist', '/station/delete', '/station/queryByIdForName', '/station/queryByIdBatch', '/station/query', '/station/queryForId', '/station/queryById', '/station/update']"})
ts_route_plan_service = CClass(service, "ts-route-plan-service", stereotype_instances = [internal], tagged_values = {'Endpoints': "['/routePlan/quickestRoute', '/routePlan/cheapestRoute', '/routePlan/minStopStations', '/welcome']", 'Port': 14578})
ts_ticketinfo_service = CClass(service, "ts-ticketinfo-service", stereotype_instances = [internal], tagged_values = {'Endpoints': "['/ticketinfo/queryForStationId', '/ticketinfo/queryForTravel', '/welcome']", 'Port': 15681})
spring_transaction_producer = CClass(service, "spring-transaction-producer", stereotype_instances = [internal])
ts_payment_service = CClass(service, "ts-payment-service", stereotype_instances = [internal], tagged_values = {'Endpoints': "['/payment/query', '/payment/pay', '/payment/addMoney', '/welcome']", 'Port': 19001})
ts_inside_payment_service = CClass(service, "ts-inside-payment-service", stereotype_instances = [internal], tagged_values = {'Port': 18673, 'Endpoints': "['/welcome', '/inside_payment/queryPayment', '/hello1_callback', '/inside_payment/payDifference', '/inside_payment/queryAddMoney', '/inside_payment/pay', '/inside_payment/queryAccount', '/inside_payment/createAccount', '/inside_payment/addMoney', '/inside_payment/drawBack']"})
rest_travel.service_update = CClass(service, "rest-travel.service-update", stereotype_instances = [internal], tagged_values = {'Port': 15100, 'Endpoints': "['/greeting']"})
sample_test_1 = CClass(service, "sample-test-1", stereotype_instances = [internal])
ts_seat_service = CClass(service, "ts-seat-service", stereotype_instances = [internal], tagged_values = {'Port': 18898, 'Endpoints': "['/seat/getSeat', '/welcome', '/seat/getLeftTicketOfInterval']"})
ts_execute_service = CClass(service, "ts-execute-service", stereotype_instances = [internal], tagged_values = {'Endpoints': "['/execute/collected', '/execute/execute', '/welcome']", 'Port': 12386})
ts_travel_plan_service = CClass(service, "ts-travel-plan-service", stereotype_instances = [internal], tagged_values = {'Port': 14322, 'Endpoints': "['/travelPlan/getMinStation', '/welcome', '/travelPlan/getCheapest', '/travelPlan/getTransferResult', '/travelPlan/getQuickest']"})
ts_travel2_service = CClass(service, "ts-travel2-service", stereotype_instances = [internal], tagged_values = {'Port': 16346, 'Endpoints': "['/travel2/adminQueryAll', '/travel2/getRouteByTripId/{tripId}', '/travel2/create', '/travel2/getTripAllDetailInfo', '/welcome', '/travel2/queryAll', '/travel2/getTripsByRouteId', '/travel2/retrieve', '/travel2/update', '/travel2/delete', '/travel2/queryWithPackage', '/travel2/getTrainTypeByTripId/{tripId}', '/travel2/query']"})
ts_travel_service = CClass(service, "ts-travel-service", stereotype_instances = [internal], tagged_values = {'Endpoints': "['/travel/getTripsByRouteId', '/welcome', '/travel/update', '/travel/getTripAllDetailInfo', '/travel/retrieve', '/travel/getRouteByTripId/{tripId}', '/travel/queryAll', '/travel/adminQueryAll', '/travel/create', '/travel/delete', '/travel/query', '/travel/queryWithPackage', '/travel/getTrainTypeByTripId/{tripId}']", 'Port': 12346})
ts_admin_order_service = CClass(service, "ts-admin-order-service", stereotype_instances = [internal], tagged_values = {'Port': 16112, 'Endpoints': "['/adminorder/addOrder', '/welcome', '/adminorder/deleteOrder', '/adminorder/findAll/{id}', '/adminorder/updateOrder']"})
ts_admin_travel_service = CClass(service, "ts-admin-travel-service", stereotype_instances = [internal], tagged_values = {'Endpoints': "['/welcome', '/admintravel/addTravel', '/admintravel/deleteTravel', '/admintravel/findAll/{id}', '/admintravel/updateTravel']", 'Port': 16114})
ts_sso_service = CClass(service, "ts-sso-service", stereotype_instances = [internal], tagged_values = {'Port': 12349, 'Endpoints': "['/welcome', '/verifyLoginToken/{token}', '/account/findAllLogin', '/account/login', '/account/modify', '/account/findById', '/account/findAll', '/logout', '/account/admindelete', '/account/adminlogin', '/account/register']"})
ts_admin_route_service = CClass(service, "ts-admin-route-service", stereotype_instances = [internal], tagged_values = {'Endpoints': "['/adminroute/findAll/{id}', '/adminroute/createAndModifyRoute', '/adminroute/deleteRoute', '/welcome']", 'Port': 16113})
rabbitmq = CClass(service, "rabbitmq", stereotype_instances = [infrastructural, message_broker], tagged_values = {'Message Broker': 'RabbitMQ', 'Port': 5672})
mongodb = CClass(service, "mongodb", stereotype_instances = [internal], tagged_values = {'Port': 27017})
zipkin = CClass(service, "zipkin", stereotype_instances = [infrastructural, tracing_server], tagged_values = {'Tracing Server': 'Zipkin', 'Port': 9411})
kafka = CClass(service, "kafka", stereotype_instances = [infrastructural, tracing_server, message_broker], tagged_values = {'Tracing Server': 'Zipkin', 'Port': 2181, 'Message Broker': 'Kafka'})
mail_server = CClass(external_component, "mail-server", stereotype_instances = [exitpoint, entrypoint, mail_server, plaintext_credentials], tagged_values = {'Username': 'fdse_microservices@163.com', 'Password': 'fdse1234', 'Host': 'smtp.163.com'})
add_links({rabbitmq: spring_transaction_consumer}, stereotype_instances = [message_consumer_rabbitmq, restful_http], tagged_values = {'Queue': 'async'})
add_links({kafka: rest_service_collector}, stereotype_instances = [restful_http, message_consumer_kafka], tagged_values = {'Consumer Topic': 'None'})
add_links({rest_service_collector: kafka}, stereotype_instances = [restful_http, message_producer_kafka], tagged_values = {'Producer Topic': 'app_log'})
add_links({ts_contacts_service: ts_sso_service}, stereotype_instances = [restful_http])
add_links({ts_admin_user_service: ts_sso_service}, stereotype_instances = [restful_http])
add_links({ts_login_service: ts_verification_code_service}, stereotype_instances = [restful_http])
add_links({ts_login_service: ts_sso_service}, stereotype_instances = [restful_http])
add_links({ts_cancel_service: ts_sso_service}, stereotype_instances = [restful_http])
add_links({ts_cancel_service: ts_notification_service}, stereotype_instances = [restful_http])
add_links({ts_cancel_service: ts_order_other_service}, stereotype_instances = [restful_http])
add_links({ts_cancel_service: ts_inside_payment_service}, stereotype_instances = [restful_http])
add_links({ts_cancel_service: ts_order_service}, stereotype_instances = [restful_http])
add_links({ts_assurance_service: ts_sso_service}, stereotype_instances = [restful_http])
add_links({ts_order_other_service: ts_sso_service}, stereotype_instances = [restful_http])
add_links({ts_order_other_service: ts_station_service}, stereotype_instances = [restful_http])
add_links({ts_preserve_service: ts_ticketinfo_service}, stereotype_instances = [restful_http])
add_links({ts_preserve_service: ts_seat_service}, stereotype_instances = [restful_http])
add_links({ts_preserve_service: ts_notification_service}, stereotype_instances = [restful_http])
add_links({ts_preserve_service: ts_sso_service}, stereotype_instances = [restful_http])
add_links({ts_preserve_service: ts_assurance_service}, stereotype_instances = [restful_http])
add_links({ts_preserve_service: ts_station_service}, stereotype_instances = [restful_http])
add_links({ts_preserve_service: ts_security_service}, stereotype_instances = [restful_http])
add_links({ts_preserve_service: ts_travel_service}, stereotype_instances = [restful_http])
add_links({ts_preserve_service: ts_contacts_service}, stereotype_instances = [restful_http])
add_links({ts_preserve_service: ts_order_service}, stereotype_instances = [restful_http])
add_links({ts_preserve_service: ts_food_service}, stereotype_instances = [restful_http])
add_links({ts_preserve_service: ts_consign_service}, stereotype_instances = [restful_http])
add_links({ts_security_service: ts_order_service}, stereotype_instances = [restful_http])
add_links({ts_security_service: ts_order_other_service}, stereotype_instances = [restful_http])
add_links({ts_consign_service: ts_consign_price_service}, stereotype_instances = [restful_http])
add_links({ts_order_service: ts_sso_service}, stereotype_instances = [restful_http])
add_links({ts_order_service: ts_station_service}, stereotype_instances = [restful_http])
add_links({ts_food_service: ts_food_map_service}, stereotype_instances = [restful_http])
add_links({ts_food_service: ts_travel_service}, stereotype_instances = [restful_http])
add_links({ts_food_service: ts_station_service}, stereotype_instances = [restful_http])
add_links({ts_rebook_service: ts_seat_service}, stereotype_instances = [restful_http])
add_links({ts_rebook_service: ts_sso_service}, stereotype_instances = [restful_http])
add_links({ts_rebook_service: ts_travel_service}, stereotype_instances = [restful_http])
add_links({ts_rebook_service: ts_travel2_service}, stereotype_instances = [restful_http])
add_links({ts_rebook_service: ts_order_service}, stereotype_instances = [restful_http])
add_links({ts_rebook_service: ts_order_other_service}, stereotype_instances = [restful_http])
add_links({ts_rebook_service: ts_station_service}, stereotype_instances = [restful_http])
add_links({ts_rebook_service: ts_inside_payment_service}, stereotype_instances = [restful_http])
add_links({ts_register_service: ts_verification_code_service}, stereotype_instances = [restful_http])
add_links({ts_register_service: ts_sso_service}, stereotype_instances = [restful_http])
add_links({ts_register_service: ts_inside_payment_service}, stereotype_instances = [restful_http])
add_links({ts_admin_basic_info_service: ts_contacts_service}, stereotype_instances = [restful_http])
add_links({ts_admin_basic_info_service: ts_station_service}, stereotype_instances = [restful_http])
add_links({ts_admin_basic_info_service: ts_train_service}, stereotype_instances = [restful_http])
add_links({ts_admin_basic_info_service: ts_config_service}, stereotype_instances = [restful_http])
add_links({ts_admin_basic_info_service: ts_price_service}, stereotype_instances = [restful_http])
add_links({ts_basic_service: ts_station_service}, stereotype_instances = [restful_http])
add_links({ts_basic_service: ts_train_service}, stereotype_instances = [restful_http])
add_links({ts_basic_service: ts_route_service}, stereotype_instances = [restful_http])
add_links({ts_basic_service: ts_price_service}, stereotype_instances = [restful_http])
add_links({ts_preserve_other_service: ts_ticketinfo_service}, stereotype_instances = [restful_http])
add_links({ts_preserve_other_service: ts_seat_service}, stereotype_instances = [restful_http])
add_links({ts_preserve_other_service: ts_notification_service}, stereotype_instances = [restful_http])
add_links({ts_preserve_other_service: ts_sso_service}, stereotype_instances = [restful_http])
add_links({ts_preserve_other_service: ts_assurance_service}, stereotype_instances = [restful_http])
add_links({ts_preserve_other_service: ts_station_service}, stereotype_instances = [restful_http])
add_links({ts_preserve_other_service: ts_security_service}, stereotype_instances = [restful_http])
add_links({ts_preserve_other_service: ts_travel2_service}, stereotype_instances = [restful_http])
add_links({ts_preserve_other_service: ts_contacts_service}, stereotype_instances = [restful_http])
add_links({ts_preserve_other_service: ts_order_other_service}, stereotype_instances = [restful_http])
add_links({ts_preserve_other_service: ts_food_service}, stereotype_instances = [restful_http])
add_links({ts_preserve_other_service: ts_consign_service}, stereotype_instances = [restful_http])
add_links({ts_route_plan_service: ts_route_service}, stereotype_instances = [restful_http])
add_links({ts_route_plan_service: ts_travel_service}, stereotype_instances = [restful_http])
add_links({ts_route_plan_service: ts_travel2_service}, stereotype_instances = [restful_http])
add_links({ts_route_plan_service: ts_station_service}, stereotype_instances = [restful_http])
add_links({ts_ticketinfo_service: ts_basic_service}, stereotype_instances = [restful_http])
add_links({ts_ticketinfo_service: ts_price_service}, stereotype_instances = [restful_http])
add_links({ts_inside_payment_service: ts_order_service}, stereotype_instances = [restful_http])
add_links({ts_inside_payment_service: ts_order_other_service}, stereotype_instances = [restful_http])
add_links({ts_inside_payment_service: ts_payment_service}, stereotype_instances = [restful_http])
add_links({ts_seat_service: ts_travel_service}, stereotype_instances = [restful_http])
add_links({ts_seat_service: ts_order_service}, stereotype_instances = [restful_http])
add_links({ts_seat_service: ts_travel2_service}, stereotype_instances = [restful_http])
add_links({ts_seat_service: ts_order_other_service}, stereotype_instances = [restful_http])
add_links({ts_seat_service: ts_config_service}, stereotype_instances = [restful_http])
add_links({ts_execute_service: ts_order_service}, stereotype_instances = [restful_http])
add_links({ts_execute_service: ts_order_other_service}, stereotype_instances = [restful_http])
add_links({ts_travel_plan_service: ts_seat_service}, stereotype_instances = [restful_http])
add_links({ts_travel_plan_service: ts_route_plan_service}, stereotype_instances = [restful_http])
add_links({ts_travel_plan_service: ts_travel_service}, stereotype_instances = [restful_http])
add_links({ts_travel_plan_service: ts_travel2_service}, stereotype_instances = [restful_http])
add_links({ts_travel_plan_service: ts_ticketinfo_service}, stereotype_instances = [restful_http])
add_links({ts_travel_plan_service: ts_station_service}, stereotype_instances = [restful_http])
add_links({ts_travel2_service: ts_ticketinfo_service}, stereotype_instances = [restful_http])
add_links({ts_travel2_service: ts_order_other_service}, stereotype_instances = [restful_http])
add_links({ts_travel2_service: ts_train_service}, stereotype_instances = [restful_http])
add_links({ts_travel2_service: ts_route_service}, stereotype_instances = [restful_http])
add_links({ts_travel2_service: ts_seat_service}, stereotype_instances = [restful_http])
add_links({ts_travel_service: ts_ticketinfo_service}, stereotype_instances = [restful_http])
add_links({ts_travel_service: ts_order_service}, stereotype_instances = [restful_http])
add_links({ts_travel_service: ts_train_service}, stereotype_instances = [restful_http])
add_links({ts_travel_service: ts_route_service}, stereotype_instances = [restful_http])
add_links({ts_travel_service: ts_seat_service}, stereotype_instances = [restful_http])
add_links({ts_admin_order_service: ts_order_service}, stereotype_instances = [restful_http])
add_links({ts_admin_order_service: ts_order_other_service}, stereotype_instances = [restful_http])
add_links({ts_admin_travel_service: ts_travel_service}, stereotype_instances = [restful_http])
add_links({ts_admin_travel_service: ts_travel2_service}, stereotype_instances = [restful_http])
add_links({ts_admin_route_service: ts_route_service}, stereotype_instances = [restful_http])
add_links({rest_service_5: rest_service_4}, stereotype_instances = [restful_http])
add_links({rest_service_2: rest_service_1}, stereotype_instances = [restful_http])
add_links({rest_service_3: rest_service_2}, stereotype_instances = [restful_http])
add_links({rest_service_3: rest_service_1}, stereotype_instances = [restful_http])
add_links({rest_service_3: rest_service_end}, stereotype_instances = [restful_http])
add_links({rest_service_3: rest_service_6}, stereotype_instances = [restful_http])
add_links({rest_service_4: rest_service_3}, stereotype_instances = [restful_http])
add_links({rest_service_6: rest_service_5}, stereotype_instances = [restful_http])
add_links({rest_service_6: rest_service_4}, stereotype_instances = [restful_http])
add_links({rest_service_6: rest_service_3}, stereotype_instances = [restful_http])
add_links({rest_service_1: rest_service_2}, stereotype_instances = [restful_http])
add_links({rest_service_5: rest_service_collector}, stereotype_instances = [restful_http])
add_links({rest_service_2: zipkin}, stereotype_instances = [restful_http])
add_links({rest_service_3: zipkin}, stereotype_instances = [restful_http])
add_links({rest_service_4: rest_service_collector}, stereotype_instances = [restful_http])
add_links({rest_service_1: zipkin}, stereotype_instances = [restful_http])
add_links({rest_service_6: rest_service_collector}, stereotype_instances = [restful_http])
add_links({rest_service_end: zipkin}, stereotype_instances = [restful_http])
add_links({ts_notification_service: mail_server}, stereotype_instances = [restful_http, plaintext_credentials_link])
model = CBundle(model_name, elements = kafka.class_object.get_connected_elements())
def run():
    generator = PlantUMLGenerator()
    generator.plant_uml_jar_path = plantuml_path
    generator.directory = output_directory
    generator.object_model_renderer.left_to_right = True
    generator.generate_object_models(model_name, [model, {}])
    print(f"Generated models in {generator.directory!s}/" + model_name)
if __name__ == "__main__":
    run()